// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhpty6GhnPqL2qIs_tl8r7ezBdGBLpvEU',
    appId: '1:479050584699:web:2e018c4b953522dbecc8de',
    messagingSenderId: '479050584699',
    projectId: 'sandbox-app-882d2',
    authDomain: 'sandbox-app-882d2.firebaseapp.com',
    storageBucket: 'sandbox-app-882d2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBepQvMrcDymDyvwIwsAlsiZUUCcZcgUOA',
    appId: '1:479050584699:android:1a9ebed1e44a4098ecc8de',
    messagingSenderId: '479050584699',
    projectId: 'sandbox-app-882d2',
    storageBucket: 'sandbox-app-882d2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJ_P4MDjUA3CABB4DdsTlRDXtR8jqh8ao',
    appId: '1:479050584699:ios:5e84af163756c012ecc8de',
    messagingSenderId: '479050584699',
    projectId: 'sandbox-app-882d2',
    storageBucket: 'sandbox-app-882d2.firebasestorage.app',
    iosBundleId: 'com.example.sandboxApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJ_P4MDjUA3CABB4DdsTlRDXtR8jqh8ao',
    appId: '1:479050584699:ios:5e84af163756c012ecc8de',
    messagingSenderId: '479050584699',
    projectId: 'sandbox-app-882d2',
    storageBucket: 'sandbox-app-882d2.firebasestorage.app',
    iosBundleId: 'com.example.sandboxApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhpty6GhnPqL2qIs_tl8r7ezBdGBLpvEU',
    appId: '1:479050584699:web:39ab2ddef12e59deecc8de',
    messagingSenderId: '479050584699',
    projectId: 'sandbox-app-882d2',
    authDomain: 'sandbox-app-882d2.firebaseapp.com',
    storageBucket: 'sandbox-app-882d2.firebasestorage.app',
  );
}
