name: Flutter CI/CD to Firebase App Distribution

on:
  push:
    branches:
      - master-release # Adjust to your default branch

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
    # Checkout code
    - name: Checkout repository
      uses: actions/checkout@v3
    
    # setup Java DEvelopment Kit
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu' # or adopt, temurin
        java-version: '17'

    # Setup Flutter
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.5'
        # flutter-version: 'stable'
    
    - name: Check Flutter version
      run: flutter --version
    
    - name: Clear Flutter cache
      run: flutter clean && flutter pub cache repair

    # Install dependencies
    - name: Install dependencies
      run: flutter pub get

    # Build APK for Android
    - name: Build Android APK
      run: flutter build apk --release

    # Build IPA for iOS
    - name: Build iOS IPA
      if: runner.os == 'macOS' # Required for iOS builds
      run: flutter build ipa --release

    # Install firebase cli
    - name: Install Firebase CLI
      run: |
        curl -sL https://firebase.tools | bash
    
    # check firebase CLI version 
    - name: Verify Firebase CLI Installation
      run: firebase --version

    # login firebase
    # - name: Authenticate Firebase CLI
    #   env:
    #     FIREBASE_AUTH_TOKEN: ${{ secrets.FIREBASE_AUTH_TOKEN }}
    #   run: |
    #     firebase login:ci --token $FIREBASE_AUTH_TOKEN

    # Upload to Firebase App Distribution for Android
    - name: Deploy Android APK to Firebase
      env:
        # FIREBASE_AUTH_TOKEN: ${{ secrets.FIREBASE_AUTH_TOKEN }}
        FIREBASE_AUTH_TOKEN: 1//0gEB1yhLwcD8DCgYIARAAGBASNwF-L9IrEFionVDtV5OOWVADNA5OS1kd3x8svYVy-ulbq6SOdIt4iv3zFSPVB4-Ln49bgnlibls
      run: |
        firebase appdistribution:distribute build/app/outputs/flutter-apk/app-release.apk \
          --app "1:479050584699:android:1a9ebed1e44a4098ecc8de"

    # Upload to Firebase App Distribution for iOS
    - name: Deploy iOS IPA to Firebase
      if: runner.os == 'macOS' # Required for iOS builds
      env:
        # FIREBASE_AUTH_TOKEN: ${{ secrets.FIREBASE_AUTH_TOKEN }}
        FIREBASE_AUTH_TOKEN: 1//0gEB1yhLwcD8DCgYIARAAGBASNwF-L9IrEFionVDtV5OOWVADNA5OS1kd3x8svYVy-ulbq6SOdIt4iv3zFSPVB4-Ln49bgnlibls
      run: |
        firebase appdistribution:distribute build/ios/ipa/Runner.ipa \
          --app "1:479050584699:ios:5e84af163756c012ecc8de"
